CREATE DATABASE 'localhost:/firebird/data/pax.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

CREATE TABLE INDICE (
    NOME  VARCHAR(50) NOT NULL PRIMARY KEY,
    VALOR INTEGER NOT NULL
);

CREATE TABLE SYNC_CONTROL (
    CORRELATION_ID CHAR(36) NOT NULL PRIMARY KEY,
    PROCESSED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTE (
    IDCLIENTE               INTEGER NOT NULL PRIMARY KEY,
    PLANO_ID                INTEGER,
    NOME                    VARCHAR(100) NOT NULL,
    CONTRATO                INTEGER NOT NULL,
    SITUACAO                INTEGER,
    DATA_CADASTRO           DATE DEFAULT CURRENT_DATE,
    CPF_CNPJ                VARCHAR(30)
);

CREATE TABLE PARCELAS_CLIENTE (
    PARCELA_ID      INTEGER NOT NULL PRIMARY KEY,
    CLIENTE_ID      INTEGER,
    VALOR_PARCELA   FLOAT,
    NUM_PARCELA     INTEGER
);

CREATE TABLE CONTATO (
    ID              INTEGER NOT NULL PRIMARY KEY,
    TIPO_PESSOA     INTEGER, 
    ID_PESSOA       INTEGER, 
    TIPO_CONTATO    INTEGER, 
    DESCRICAO       VARCHAR(100)
);

CREATE TABLE FB_SYNC_OUTBOX (
    ID          BIGINT NOT NULL PRIMARY KEY,
    TABLE_NAME  VARCHAR(31) NOT NULL,
    OP_TYPE     CHAR(1) NOT NULL,    -- I (Insert), U (Update), D (Delete)
    PK_VALUE    VARCHAR(100) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE GENERATOR GEN_FB_SYNC_OUTBOX_ID;
SET GENERATOR GEN_FB_SYNC_OUTBOX_ID TO 0;

SET TERM ^ ;

CREATE TRIGGER TR_FB_SYNC_OUTBOX_BI FOR FB_SYNC_OUTBOX
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR GEN_FB_SYNC_OUTBOX_ID;
END^

CREATE TRIGGER TR_SYNC_CLIENTE_ADU FOR CLIENTE
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 99
AS
DECLARE VARIABLE PK_VAR INTEGER;
DECLARE VARIABLE OP_VAR CHAR(1);
BEGIN
    /* PROTEÇÃO DE LOOPBACK INFINITO: 
       Se o usuário logado for o 'SYNC_USER', significa que a mudança 
       veio da API, então não precisamos reenviá-la para lá
    */
    IF (CURRENT_USER = 'SYNC_USER') THEN EXIT;

    IF (INSERTING) THEN 
    BEGIN
        OP_VAR = 'I';
        PK_VAR = NEW.IDCLIENTE;
    END
    ELSE IF (UPDATING) THEN 
    BEGIN
        OP_VAR = 'U';
        PK_VAR = NEW.IDCLIENTE;
    END
    ELSE IF (DELETING) THEN 
    BEGIN
        OP_VAR = 'D';
        PK_VAR = OLD.IDCLIENTE;
    END

    INSERT INTO FB_SYNC_OUTBOX (TABLE_NAME, OP_TYPE, PK_VALUE)
    VALUES ('CLIENTE', :OP_VAR, CAST(:PK_VAR AS VARCHAR(100)));
END^

SET TERM ; ^

/* 5. CARGA INICIAL DE DADOS */

INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CLIENTE_ID', 2034);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CONTATO_ID', 8800);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_PARCELAS_CLIENTE', 136150);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CONTRATO', 24098);

COMMIT;