CREATE TABLE INDICE (
    NOME  VARCHAR(50) NOT NULL PRIMARY KEY,
    VALOR INTEGER NOT NULL
);

CREATE TABLE SYNC_CONTROL (
    CORRELATION_ID CHAR(36) NOT NULL PRIMARY KEY,
    PROCESSED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTE (
    IDCLIENTE               INTEGER NOT NULL PRIMARY KEY,
    PLANO_ID                INTEGER,
    NOME                    VARCHAR(100) NOT NULL,
    CONTRATO                INTEGER NOT NULL,
    SITUACAO                INTEGER,
    DATA_CADASTRO           DATE DEFAULT CURRENT_DATE,
    CPF_CNPJ                VARCHAR(30)
);

CREATE TABLE PARCELAS_CLIENTE (
    PARCELA_ID      INTEGER NOT NULL PRIMARY KEY,
    CLIENTE_ID      INTEGER,
    VALOR_PARCELA   FLOAT,
    NUM_PARCELA     INTEGER
);

CREATE TABLE CONTATO (
    ID              INTEGER NOT NULL PRIMARY KEY,
    TIPO_PESSOA     INTEGER, 
    ID_PESSOA       INTEGER, 
    TIPO_CONTATO    INTEGER, 
    DESCRICAO       VARCHAR(100)
);

INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CLIENTE_ID', 2034);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CONTATO_ID', 8800);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_PARCELAS_CLIENTE', 136150);
INSERT INTO INDICE (NOME, VALOR) VALUES ('GEN_CONTRATO', 24098);